[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.4.0"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.5.0"

[[constraint]]
  name = "github.com/electronicpanopticon/gobrick"
  version = "0.0.0"
